### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by sergeevabc** [prologic/fish#2]
Two years [later][1], I am still lost because of poor documentation and lack of examples. 
Command `fish -e file.txt` outputs a blank screen with no properly labeled prompt (like OpenSSL does, for example).
Then I type something in that darkness and get `error reading key: %!s(<nil>) `.

[1]: https://github.com/prologic/fish/issues/1

**Comment by prologic** [comment]
I'll try to improve this. Sorry it was not written initially for human consumption but more for understanding the crypto libs.

I'll try to refactor the code and build a new friendlier interface 👌

**Comment by prologic** [comment]
You are right, this _sucks_:

```#!console
$ ./fish -e foo.txt
2021/03/17 18:19:45 error reading key: %!s(<nil>)
```

😢

**Comment by prologic** [comment]
How's this?

```#!console
(⎈ |local:default)
prologic@Jamess-iMac
Wed Mar 17 20:15:25
~/Projects/fish
 (improved_cli) 130
$ ./fish -e foo.txt
Enter encryption key:
��nGX�����kZ�(⎈ |local:default)
prologic@Jamess-iMac
Wed Mar 17 20:15:30
~/Projects/fish
 (improved_cli) 0
$ ./fish -k foobar -e foo.txt
��nGX�����kZ�(⎈ |local:default)
prologic@Jamess-iMac
Wed Mar 17 20:15:37
~/Projects/fish
 (improved_cli) 0
$ ./fish -k foobar -e foo.txt | ./fish -k foobar -d -
hello world
```
